spring.profiles.active=dev
#spring.profiles.active=qa

spring.application.name=DynamicFormBuilder
jwt.secret=5aBv7w6n9eQp3KzLmRt8VxYuTzWsXcYz
jwt.expiration=3600000

# Database Configuration
server.port=8081
#Database Configuration


#spring.datasource.url=jdbc:mysql://localhost:3306/test_db  (for mysql)
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


server.error.include-message=always

# Redis Configuration
spring.redis.port=6380
spring.redis.password=   # If Redis has a password set, add it here (leave empty if no password)


# Expose all actuator endpoints via HTTP
management.endpoints.web.exposure.include=*

# Enable specific actuator endpoints
management.endpoint.health.enabled=true
management.endpoint.caches.enabled=true
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true

management.metrics.export.prometheus.enabled=true
management.endpoints.web.base-path=/actuator


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=misogi936@gmail.com
spring.mail.password=zefzuvogezjuaoce

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true











